# Generated by Django 5.1 on 2024-08-20 05:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='No name available', max_length=255)),
                ('description', models.TextField(default='No description available')),
                ('fridge_id', models.CharField(default='No fridge ID', max_length=50)),
                ('model_number', models.CharField(default='No model number', max_length=50)),
                ('serial_number', models.CharField(default='No serial number', max_length=50)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('installation_date', models.DateField(blank=True, null=True)),
                ('warranty_expiry_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, default='No location', max_length=100, null=True)),
            ],
        ),
    ]
